CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company VARCHAR(255) NOT NULL,
  contact VARCHAR(255),
  email   VARCHAR(255),
  phone   VARCHAR(50),
  budget  INT DEFAULT 0,
  timeline VARCHAR(16) DEFAULT 'mid',
  authority TINYINT(1) DEFAULT 0,
  tech_fit INT DEFAULT 5,
  need TEXT,
  notes TEXT,
  score INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
